<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitProfiler
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\Profiler\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Profiler\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\Profiler\\AppInfo\\Application' => __DIR__ . '/..' . '/../lib/AppInfo/Application.php',
        'OCA\\Profiler\\Command\\Disable' => __DIR__ . '/..' . '/../lib/Command/Disable.php',
        'OCA\\Profiler\\Command\\Enable' => __DIR__ . '/..' . '/../lib/Command/Enable.php',
        'OCA\\Profiler\\Controller\\DatabaseProfilerController' => __DIR__ . '/..' . '/../lib/Controller/DatabaseProfilerController.php',
        'OCA\\Profiler\\Controller\\MainController' => __DIR__ . '/..' . '/../lib/Controller/MainController.php',
        'OCA\\Profiler\\DataCollector\\EventLoggerDataProvider' => __DIR__ . '/..' . '/../lib/DataCollector/EventLoggerDataProvider.php',
        'OCA\\Profiler\\DataCollector\\HttpDataCollector' => __DIR__ . '/..' . '/../lib/DataCollector/HttpDataCollector.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitProfiler::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitProfiler::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitProfiler::$classMap;

        }, null, ClassLoader::class);
    }
}
